// GENERATED by tools/gen-menus.js from the Code::Blocks XRC resources.
// Do not edit by hand; re-run the generator instead.
const CB_MENUS = [
 {
  "id": "file_menu",
  "label": "File",
  "mnemonic": 0,
  "items": [
   {
    "type": "menu",
    "id": "idFileNew",
    "label": "New",
    "mnemonic": -1,
    "items": [
     {
      "type": "item",
      "id": "idFileNewEmpty",
      "label": "Empty file",
      "mnemonic": -1,
      "accel": "Ctrl-Shift-N",
      "help": "Quickly create a new empty file"
     },
     {
      "type": "sep"
     },
     {
      "type": "item",
      "id": "idFileNewProject",
      "label": "Project...",
      "mnemonic": -1,
      "help": "Create a new project"
     },
     {
      "type": "item",
      "id": "idFileNewTarget",
      "label": "Build target...",
      "mnemonic": -1,
      "help": "Create a new build target for the active project"
     },
     {
      "type": "item",
      "id": "idFileNewFile",
      "label": "File...",
      "mnemonic": -1,
      "help": "Create a new file"
     },
     {
      "type": "item",
      "id": "idFileNewCustom",
      "label": "Custom...",
      "mnemonic": -1,
      "help": "Create a new custom something :-)"
     },
     {
      "type": "item",
      "id": "idFileNewUser",
      "label": "From template...",
      "mnemonic": -1,
      "help": "Create a new project based on a previously saved template"
     }
    ]
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idFileOpen",
    "label": "Open...",
    "mnemonic": 0,
    "accel": "Ctrl-O",
    "help": "Open a file or project",
    "bitmap": "core/file_open"
   },
   {
    "type": "item",
    "id": "idFileOpenDefWorkspace",
    "label": "Open default workspace",
    "mnemonic": -1,
    "help": "Open the default workspace"
   },
   {
    "type": "menu",
    "id": "idFileReopenProject",
    "label": "Recent projects",
    "mnemonic": 0,
    "items": [
     {
      "type": "item",
      "id": "idFileOpenRecentProjectClearHistory",
      "label": "Clear history",
      "mnemonic": 0,
      "help": "Clear the recent projects list",
      "bitmap": "core/history_clear"
     }
    ]
   },
   {
    "type": "menu",
    "id": "idFileReopenFile",
    "label": "Recent files",
    "mnemonic": 1,
    "items": [
     {
      "type": "item",
      "id": "idFileOpenRecentFileClearHistory",
      "label": "Clear history",
      "mnemonic": 0,
      "help": "Clear the recent files list",
      "bitmap": "core/history_clear"
     }
    ]
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idFileSave",
    "label": "Save file",
    "mnemonic": 0,
    "accel": "Ctrl-S",
    "help": "Save the active file",
    "bitmap": "core/file_save"
   },
   {
    "type": "item",
    "id": "idFileSaveAs",
    "label": "Save file as...",
    "mnemonic": 10,
    "help": "Save the active file under a different name",
    "bitmap": "core/file_save_as"
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idFileSaveProject",
    "label": "Save project",
    "mnemonic": -1,
    "help": "Save active project"
   },
   {
    "type": "item",
    "id": "idFileSaveProjectAs",
    "label": "Save project as...",
    "mnemonic": 2,
    "help": "Save active project under a different name"
   },
   {
    "type": "item",
    "id": "idFileSaveProjectTemplate",
    "label": "Save project as template...",
    "mnemonic": -1,
    "help": "Keep this project as a template to base new projects on"
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idFileSaveWorkspace",
    "label": "Save workspace",
    "mnemonic": 5,
    "help": "Save current workspace"
   },
   {
    "type": "item",
    "id": "idFileSaveWorkspaceAs",
    "label": "Save workspace as...",
    "mnemonic": 8,
    "help": "Save current workspace under a different name"
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idFileSaveAll",
    "label": "Save everything",
    "mnemonic": -1,
    "accel": "Ctrl-Shift-S",
    "help": "Save all source files, projects and the workspace, if there are changes to them. Save the configuration",
    "bitmap": "core/file_save_all"
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idFileClose",
    "label": "Close file",
    "mnemonic": 0,
    "accel": "Ctrl-W",
    "help": "Close the active file",
    "bitmap": "core/file_close"
   },
   {
    "type": "item",
    "id": "idFileCloseAll",
    "label": "Close all files",
    "mnemonic": -1,
    "accel": "Ctrl-Shift-W",
    "help": "Close all open files"
   },
   {
    "type": "item",
    "id": "idFileCloseProject",
    "label": "Close project",
    "mnemonic": -1,
    "help": "Close active project"
   },
   {
    "type": "item",
    "id": "idFileCloseWorkspace",
    "label": "Close workspace",
    "mnemonic": -1,
    "help": "Close current workspace"
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idFilePrint",
    "label": "Print...",
    "mnemonic": -1,
    "accel": "Ctrl-P",
    "bitmap": "core/file_print"
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idMenuFileProperties",
    "label": "Properties...",
    "mnemonic": -1
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idFileExit",
    "label": "Quit",
    "mnemonic": 0,
    "accel": "Ctrl-Q",
    "help": "Exit Code::Blocks",
    "bitmap": "core/exit"
   }
  ]
 },
 {
  "id": "edit_menu",
  "label": "Edit",
  "mnemonic": 0,
  "items": [
   {
    "type": "item",
    "id": "idEditUndo",
    "label": "Undo",
    "mnemonic": 0,
    "accel": "Ctrl-Z",
    "help": "Undo the last editing operation",
    "bitmap": "core/undo"
   },
   {
    "type": "item",
    "id": "idEditRedo",
    "label": "Redo",
    "mnemonic": 0,
    "accel": "Ctrl-Shift-Z",
    "help": "Redo the last editing operation",
    "bitmap": "core/redo"
   },
   {
    "type": "item",
    "id": "idEditClearHistory",
    "label": "Clear changes history",
    "mnemonic": -1,
    "help": "Clear the undo-/redo- and (if exists) changebar-history",
    "bitmap": "core/history_clear"
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idEditCut",
    "label": "Cut",
    "mnemonic": 2,
    "help": "Copy selected text to clipboard and erase it",
    "bitmap": "core/edit_cut"
   },
   {
    "type": "item",
    "id": "idEditCopy",
    "label": "Copy",
    "mnemonic": 0,
    "help": "Copy selected text to clipboard",
    "bitmap": "core/edit_copy"
   },
   {
    "type": "item",
    "id": "idEditPaste",
    "label": "Paste",
    "mnemonic": 0,
    "help": "Paste text from clipboard",
    "bitmap": "core/edit_paste"
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idEditSwapHeaderSource",
    "label": "Swap header/source",
    "mnemonic": 1,
    "accel": "F11",
    "help": "Swap between header and source file pair"
   },
   {
    "type": "sep"
   },
   {
    "type": "menu",
    "id": "idEditHighlightMode",
    "label": "Highlight mode",
    "mnemonic": 0,
    "items": [
     {
      "type": "item",
      "id": "idEditHighlightModeText",
      "label": "Plain text",
      "mnemonic": -1,
      "help": "Switch highlighting mode for current document to \"Plain text\"",
      "radio": true
     },
     {
      "type": "item",
      "id": "idEditHighlightModeCpp",
      "label": "C/C++",
      "mnemonic": -1
     }
    ]
   },
   {
    "type": "menu",
    "id": "idEditBookmarks",
    "label": "Bookmarks",
    "mnemonic": 0,
    "items": [
     {
      "type": "item",
      "id": "idEditBookmarksToggle",
      "label": "Toggle bookmark",
      "mnemonic": 0,
      "accel": "Ctrl-B",
      "help": "Toggle a bookmark for the current position",
      "bitmap": "core/bookmark_add"
     },
     {
      "type": "item",
      "id": "idEditBookmarksPrevious",
      "label": "Goto previous bookmark",
      "mnemonic": 5,
      "accel": "Alt-PgUp",
      "help": "Goto previous bookmark"
     },
     {
      "type": "item",
      "id": "idEditBookmarksNext",
      "label": "Goto next bookmark",
      "mnemonic": 5,
      "accel": "Alt-PgDn",
      "help": "Goto next bookmark"
     },
     {
      "type": "item",
      "id": "idEditBookmarksClearAll",
      "label": "Clear all bookmarks",
      "mnemonic": 6,
      "help": "Clear all bookmarks"
     }
    ]
   },
   {
    "type": "menu",
    "id": "idEditFolding",
    "label": "Folding",
    "mnemonic": 0,
    "items": [
     {
      "type": "item",
      "id": "idEditFoldAll",
      "label": "Fold all",
      "mnemonic": -1
     },
     {
      "type": "item",
      "id": "idEditUnfoldAll",
      "label": "Unfold all",
      "mnemonic": -1
     },
     {
      "type": "item",
      "id": "idEditFoldAll",
      "label": "Fold all",
      "mnemonic": 5,
      "help": "Fold all"
     },
     {
      "type": "item",
      "id": "idEditUnfoldAll",
      "label": "Unfold all",
      "mnemonic": 0,
      "help": "Unfold all"
     },
     {
      "type": "item",
      "id": "idEditToggleAllFolds",
      "label": "Toggle all",
      "mnemonic": 0,
      "accel": "Shift-F12",
      "help": "Toggle all folds"
     },
     {
      "type": "sep"
     },
     {
      "type": "item",
      "id": "idEditFoldBlock",
      "label": "Fold current block",
      "mnemonic": 5,
      "help": "Fold current block"
     },
     {
      "type": "item",
      "id": "idEditUnfoldBlock",
      "label": "Unfold current block",
      "mnemonic": 9,
      "help": "Unfold current block"
     },
     {
      "type": "item",
      "id": "idEditToggleFoldBlock",
      "label": "Toggle current block",
      "mnemonic": 15,
      "accel": "F12",
      "help": "Toggle folding of current block"
     }
    ]
   },
   {
    "type": "menu",
    "id": "idEditEOLMode",
    "label": "End-of-line mode",
    "mnemonic": 0,
    "items": [
     {
      "type": "item",
      "id": "idEditEOLCRLF",
      "label": "Windows (CR & LF)",
      "mnemonic": -1,
      "help": "End-of-line mode uses carriage return and line feed",
      "radio": true
     },
     {
      "type": "item",
      "id": "idEditEOLCR",
      "label": "Mac (CR)",
      "mnemonic": -1,
      "help": "End-of-line mode uses carriage return only",
      "radio": true
     },
     {
      "type": "item",
      "id": "idEditEOLLF",
      "label": "Unix (LF)",
      "mnemonic": -1,
      "help": "End-of-line mode uses line feed only",
      "radio": true
     }
    ]
   },
   {
    "type": "menu",
    "id": "idEditEncoding",
    "label": "File encoding",
    "mnemonic": -1,
    "items": [
     {
      "type": "item",
      "id": "idEditEncodingDefault",
      "label": "System default",
      "mnemonic": -1,
      "help": "Use the system default encoding",
      "checkable": true
     },
     {
      "type": "item",
      "id": "idEditEncodingUseBom",
      "label": "Save byte-order-mark (BOM)",
      "mnemonic": -1,
      "help": "Save the Unicode encoding in a BOM",
      "checkable": true
     },
     {
      "type": "sep"
     },
     {
      "type": "item",
      "id": "idEditEncodingAscii",
      "label": "ASCII (ISO-8859-1)",
      "mnemonic": -1,
      "help": "Use the ISO-8859-1 character encoding",
      "checkable": true
     },
     {
      "type": "item",
      "id": "idEditEncodingUtf7",
      "label": "UTF-7",
      "mnemonic": -1,
      "help": "Use the UTF-7 character encoding",
      "checkable": true
     },
     {
      "type": "item",
      "id": "idEditEncodingUtf8",
      "label": "UTF-8",
      "mnemonic": -1,
      "help": "Use the UTF-8 character encoding",
      "checkable": true
     },
     {
      "type": "sep"
     },
     {
      "type": "item",
      "id": "idEditEncodingUnicode",
      "label": "Unicode default",
      "mnemonic": -1,
      "help": "Use the system default Unicode character encoding",
      "checkable": true
     },
     {
      "type": "item",
      "id": "idEditEncodingUtf16",
      "label": "Native UTF-16",
      "mnemonic": -1,
      "help": "Use the native UTF-16 character encoding",
      "checkable": true
     },
     {
      "type": "item",
      "id": "idEditEncodingUtf32",
      "label": "Native UTF-32",
      "mnemonic": -1,
      "help": "Use the native UTF-32 character encoding",
      "checkable": true
     },
     {
      "type": "sep"
     },
     {
      "type": "item",
      "id": "idEditEncodingUnicode16BE",
      "label": "Unicode 16-bit big-endian",
      "mnemonic": -1,
      "help": "Use the Unicode 16-bit big-endian multi-byte encoding",
      "checkable": true
     },
     {
      "type": "item",
      "id": "idEditEncodingUnicode16LE",
      "label": "Unicode 16-bit little-endian",
      "mnemonic": -1,
      "help": "Use the Unicode 16-bit little-endian multi-byte encoding",
      "checkable": true
     },
     {
      "type": "item",
      "id": "idEditEncodingUnicode32BE",
      "label": "Unicode 32-bit big-endian",
      "mnemonic": -1,
      "help": "Use the Unicode 32-bit big-endian multi-byte encoding",
      "checkable": true
     },
     {
      "type": "item",
      "id": "idEditEncodingUnicode32LE",
      "label": "Unicode 32-bit little-endian",
      "mnemonic": -1,
      "help": "Use the Unicode 32-bit little-endian multi-byte encoding",
      "checkable": true
     }
    ]
   },
   {
    "type": "menu",
    "id": "idEditSpecialCommands",
    "label": "Special commands",
    "mnemonic": -1,
    "items": [
     {
      "type": "menu",
      "id": "idEditSpecialCommandsMovement",
      "label": "Movement",
      "mnemonic": -1,
      "items": [
       {
        "type": "item",
        "id": "idEditParaUp",
        "label": "Paragraph up",
        "mnemonic": -1,
        "help": "Move caret one paragraph up"
       },
       {
        "type": "item",
        "id": "idEditParaUpExtend",
        "label": "Paragraph up, extending selection",
        "mnemonic": -1,
        "help": "Move caret one paragraph up and extend the selection"
       },
       {
        "type": "item",
        "id": "idEditParaDown",
        "label": "Paragraph down",
        "mnemonic": -1,
        "help": "Move caret one paragraph down"
       },
       {
        "type": "item",
        "id": "idEditParaDownExtend",
        "label": "Paragraph down, extending selection",
        "mnemonic": -1,
        "help": "Move caret one paragraph down while extend the selection"
       },
       {
        "type": "sep"
       },
       {
        "type": "item",
        "id": "idEditWordPartLeft",
        "label": "Wordpart left",
        "mnemonic": -1,
        "help": "Move caret one wordpart to the left"
       },
       {
        "type": "item",
        "id": "idEditWordPartLeftExtend",
        "label": "Wordpart left, extending selection",
        "mnemonic": -1,
        "help": "Move caret one wordpart to the left and extend the selection"
       },
       {
        "type": "item",
        "id": "idEditWordPartRight",
        "label": "Wordpart right",
        "mnemonic": -1,
        "help": "Move caret one wordpart to the right"
       },
       {
        "type": "item",
        "id": "idEditWordPartRightExtend",
        "label": "Wordpart right, extending selection",
        "mnemonic": -1,
        "help": "Move caret one wordpart to the right and extend the selection"
       }
      ]
     },
     {
      "type": "menu",
      "id": "idEditSpecialCommandsZoom",
      "label": "Zoom",
      "mnemonic": -1,
      "items": [
       {
        "type": "item",
        "id": "idEditZoomIn",
        "label": "In",
        "mnemonic": -1,
        "help": "Increase font size"
       },
       {
        "type": "item",
        "id": "idEditZoomOut",
        "label": "Out",
        "mnemonic": -1,
        "help": "Decrease font size"
       },
       {
        "type": "item",
        "id": "idEditZoomReset",
        "label": "Reset",
        "mnemonic": -1,
        "help": "Set default font size"
       }
      ]
     },
     {
      "type": "menu",
      "id": "idEditSpecialCommandsLine",
      "label": "Line",
      "mnemonic": -1,
      "items": [
       {
        "type": "item",
        "id": "idEditLineDuplicate",
        "label": "Duplicate",
        "mnemonic": -1,
        "help": "Duplicate current line"
       },
       {
        "type": "item",
        "id": "idEditLineCut",
        "label": "Cut",
        "mnemonic": -1,
        "help": "Cut current line"
       },
       {
        "type": "item",
        "id": "idEditLineDelete",
        "label": "Delete",
        "mnemonic": -1,
        "help": "Delete current line"
       },
       {
        "type": "item",
        "id": "idEditLineTranspose",
        "label": "Transpose",
        "mnemonic": -1,
        "help": "Transpose current line with previous line"
       },
       {
        "type": "item",
        "id": "idEditLineCopy",
        "label": "Copy",
        "mnemonic": -1,
        "help": "Copy current line"
       },
       {
        "type": "item",
        "id": "idEditLinePaste",
        "label": "Paste",
        "mnemonic": -1,
        "help": "Paste before current line"
       },
       {
        "type": "item",
        "id": "idEditLineUp",
        "label": "Move up",
        "mnemonic": -1,
        "accel": "Alt-UP",
        "help": "Transpose current line(s) up"
       },
       {
        "type": "item",
        "id": "idEditLineDown",
        "label": "Move down",
        "mnemonic": -1,
        "accel": "Alt-DOWN",
        "help": "Transpose current line(s) down"
       }
      ]
     },
     {
      "type": "menu",
      "id": "idEditSpecialCommandsCase",
      "label": "Case",
      "mnemonic": -1,
      "items": [
       {
        "type": "item",
        "id": "idEditUpperCase",
        "label": "Uppercase",
        "mnemonic": -1,
        "help": "Make selection uppercase"
       },
       {
        "type": "item",
        "id": "idEditLowerCase",
        "label": "Lowercase",
        "mnemonic": -1,
        "help": "Make selection lowercase"
       }
      ]
     },
     {
      "type": "menu",
      "id": "idEditSpecialCommandsOther",
      "label": "Other",
      "mnemonic": -1,
      "items": [
       {
        "type": "item",
        "id": "idEditInsertNewLine",
        "label": "Insert new line",
        "mnemonic": -1,
        "accel": "Shift+Return",
        "help": "Insert line below current line"
       },
       {
        "type": "item",
        "id": "idEditGotoLineEnd",
        "label": "Goto line end",
        "mnemonic": -1,
        "accel": "Ctrl+Return",
        "help": "Goto current line end"
       },
       {
        "type": "item",
        "id": "idEditInsertNewLineBelow",
        "label": "Insert unindented line below current line",
        "mnemonic": -1,
        "help": "Insert line below current line without indentation"
       },
       {
        "type": "item",
        "id": "idEditInsertNewLineAbove",
        "label": "Insert unindented line above current line",
        "mnemonic": -1,
        "help": "Insert line above current line without indentation"
       }
      ]
     }
    ]
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idEditSelectAll",
    "label": "Select all",
    "mnemonic": 7,
    "help": "Selects the entire text range"
   },
   {
    "type": "item",
    "id": "idEditSelectNext",
    "label": "Select next occurrence",
    "mnemonic": 0,
    "accel": "Ctrl-E",
    "help": "Selects the next occurrence of the currently selected text. Allows editing all the occurrences."
   },
   {
    "type": "item",
    "id": "idEditSelectNextSkip",
    "label": "Select skip to next occurrence",
    "mnemonic": 0,
    "accel": "Shift-Ctrl-E",
    "help": "Deselects the current text and then selects the next occurrence of the same text. Allows editing all the occurrences."
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idEditCommentSelected",
    "label": "Comment",
    "mnemonic": 5,
    "accel": "Shift-Ctrl-C",
    "help": "Comments the selected block of code"
   },
   {
    "type": "item",
    "id": "idEditUncommentSelected",
    "label": "Uncomment",
    "mnemonic": 7,
    "accel": "Shift-Ctrl-X",
    "help": "Uncomments the selected block of code"
   },
   {
    "type": "item",
    "id": "idEditToggleCommentSelected",
    "label": "Toggle comment",
    "mnemonic": 12,
    "help": "Toggles the commentation of the selected block of code"
   },
   {
    "type": "item",
    "id": "idEditStreamCommentSelected",
    "label": "Stream-comment",
    "mnemonic": 12,
    "help": "Comments the selected code"
   },
   {
    "type": "item",
    "id": "idEditBoxCommentSelected",
    "label": "Box-comment",
    "mnemonic": 9,
    "help": "Boxcomments the selected lines of code"
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idEditGotoMatchingBrace",
    "label": "Goto matching brace",
    "mnemonic": -1,
    "accel": "Ctrl-Shift-B",
    "help": "Moves the caret to the matching brace (if any)"
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idEditShowCallTip",
    "label": "Show call tip",
    "mnemonic": -1,
    "accel": "Ctrl-Shift-Space"
   }
  ]
 },
 {
  "id": "menu_view",
  "label": "View",
  "mnemonic": 0,
  "items": [
   {
    "type": "menu",
    "id": "idViewLayouts",
    "label": "Perspectives",
    "mnemonic": -1,
    "items": [
     {
      "type": "sep"
     },
     {
      "type": "item",
      "id": "idViewLayoutSave",
      "label": "Save current",
      "mnemonic": -1,
      "help": "Save current perspective"
     },
     {
      "type": "item",
      "id": "idViewLayoutDelete",
      "label": "Delete current",
      "mnemonic": -1,
      "help": "Delete current perspective"
     }
    ]
   },
   {
    "type": "menu",
    "id": "idViewToolbars",
    "label": "Toolbars",
    "mnemonic": -1,
    "items": [
     {
      "type": "item",
      "id": "idViewToolFit",
      "label": "Fit toolbars",
      "mnemonic": 0,
      "help": "Try to reorder toolbars in such a way that all of them are visible"
     },
     {
      "type": "item",
      "id": "idViewToolOptimize",
      "label": "Optimize toolbars",
      "mnemonic": 0,
      "help": "Try to reorder the toolbars in such a way that the use minimum space"
     },
     {
      "type": "sep"
     },
     {
      "type": "item",
      "id": "idViewToolMain",
      "label": "Main",
      "mnemonic": 0,
      "help": "Show/hide main toolbar",
      "checkable": true
     },
     {
      "type": "item",
      "id": "idViewToolDebugger",
      "label": "Debugger",
      "mnemonic": 0,
      "help": "Show/hide debugger toolbar",
      "checkable": true
     },
     {
      "type": "item",
      "id": "idViewToolCompiler",
      "label": "Compiler",
      "mnemonic": -1,
      "checkable": true,
      "checked": true
     }
    ]
   },
   {
    "type": "item",
    "id": "idViewManager",
    "label": "Manager",
    "mnemonic": 0,
    "accel": "Shift-F2",
    "help": "Show/hide manager",
    "checkable": true
   },
   {
    "type": "item",
    "id": "idViewLogManager",
    "label": "Logs",
    "mnemonic": 0,
    "accel": "F2",
    "help": "Show/hide logs",
    "checkable": true
   },
   {
    "type": "item",
    "id": "idViewStartPage",
    "label": "Start Page",
    "mnemonic": 6,
    "help": "Show/hide start page",
    "checkable": true
   },
   {
    "type": "item",
    "id": "idViewScriptConsole",
    "label": "Script console",
    "mnemonic": 1,
    "help": "Show/hide the script console",
    "checkable": true
   },
   {
    "type": "item",
    "id": "idViewHideEditorTabs",
    "label": "Hide editor tabs",
    "mnemonic": -1,
    "help": "Show/hide the editor tabs",
    "checkable": true
   },
   {
    "type": "item",
    "id": "idViewStatusbar",
    "label": "Status bar",
    "mnemonic": 0,
    "help": "Show/hide status bar",
    "checkable": true
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idViewFullScreen",
    "label": "Full screen",
    "mnemonic": 1,
    "accel": "SHIFT-F11",
    "help": "Switch to full screen view",
    "checkable": true
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idViewFocusEditor",
    "label": "Focus editor",
    "mnemonic": -1,
    "help": "Set focus on the active editor"
   },
   {
    "type": "item",
    "id": "idViewFocusManagement",
    "label": "Focus management panel",
    "mnemonic": -1,
    "help": "Set focus on the management panel"
   },
   {
    "type": "item",
    "id": "idViewFocusLogsAndOthers",
    "label": "Focus logs and others",
    "mnemonic": -1,
    "help": "Set focus on the logs and others panel"
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idViewSwitchTabs",
    "label": "Switch tabs",
    "mnemonic": 1,
    "accel": "Ctrl+Tab",
    "help": "Switch between open editor tabs"
   }
  ]
 },
 {
  "id": "menu_search",
  "label": "Search",
  "mnemonic": 3,
  "items": [
   {
    "type": "item",
    "id": "idSearchFind",
    "label": "Find...",
    "mnemonic": 0,
    "accel": "Ctrl-F",
    "help": "Search for text",
    "bitmap": "core/find"
   },
   {
    "type": "item",
    "id": "idSearchFindInFiles",
    "label": "Find in files...",
    "mnemonic": 11,
    "accel": "Ctrl-Shift-F",
    "help": "Search for text",
    "bitmap": "core/find_in_files"
   },
   {
    "type": "item",
    "id": "idSearchFindNext",
    "label": "Find next",
    "mnemonic": 5,
    "accel": "F3",
    "help": "Repeat the last search in the same direction",
    "bitmap": "core/find_next"
   },
   {
    "type": "item",
    "id": "idSearchFindPrevious",
    "label": "Find previous",
    "mnemonic": 5,
    "accel": "Shift-F3",
    "help": "Repeat the last search in the opposite direction",
    "bitmap": "core/find_prev"
   },
   {
    "type": "item",
    "id": "idSearchFindSelectedNext",
    "label": "Find next selected",
    "mnemonic": 5,
    "help": "Search for selected text in the same direction",
    "bitmap": "core/find_next"
   },
   {
    "type": "item",
    "id": "idSearchFindSelectedPrevious",
    "label": "Find previous selected",
    "mnemonic": 5,
    "help": "Search for selected text in the opposite direction",
    "bitmap": "core/find_prev"
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idSearchReplace",
    "label": "Replace...",
    "mnemonic": 0,
    "accel": "Ctrl-R",
    "help": "Find and replace text",
    "bitmap": "core/search_replace"
   },
   {
    "type": "item",
    "id": "idSearchReplaceInFiles",
    "label": "Replace in files...",
    "mnemonic": 15,
    "accel": "Ctrl-Shift-R",
    "help": "Find and replace text",
    "bitmap": "core/search_replace_in_files"
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idSearchGotoLine",
    "label": "Goto line...",
    "mnemonic": 5,
    "accel": "Ctrl-G",
    "help": "Goto a specific line",
    "bitmap": "core/goto"
   },
   {
    "type": "item",
    "id": "idSearchGotoNextChanged",
    "label": "Goto next changed line",
    "mnemonic": -1,
    "accel": "Ctrl-F3",
    "help": "Goto next changed line",
    "bitmap": "core/find_next"
   },
   {
    "type": "item",
    "id": "idSearchGotoPreviousChanged",
    "label": "Goto previous changed line",
    "mnemonic": -1,
    "accel": "Ctrl-Shift-F3",
    "help": "Goto previous changed line",
    "bitmap": "core/find_prev"
   },
   {
    "type": "item",
    "id": "idMenuGotoFile",
    "label": "Goto file...",
    "mnemonic": -1,
    "accel": "Alt-G"
   }
  ]
 },
 {
  "id": "menu_project",
  "label": "Project",
  "mnemonic": 0,
  "items": [
   {
    "type": "item",
    "id": "idMenuAddFile",
    "label": "Add files...",
    "mnemonic": -1,
    "help": "Add files to the project"
   },
   {
    "type": "item",
    "id": "idMenuAddFilesRecursively",
    "label": "Add files recursively...",
    "mnemonic": -1,
    "help": "Add files recursively to the project"
   },
   {
    "type": "item",
    "id": "idMenuManageGlobs",
    "label": "Automatic source paths...",
    "mnemonic": -1,
    "help": "Manage automatic source paths"
   },
   {
    "type": "item",
    "id": "idMenuRemoveFile",
    "label": "Remove files...",
    "mnemonic": -1,
    "help": "Remove files from the project"
   },
   {
    "type": "sep"
   },
   {
    "type": "menu",
    "id": "idMenuProjectTreeProps",
    "label": "Project tree",
    "mnemonic": -1,
    "items": [
     {
      "type": "item",
      "id": "idMenuProjectUp",
      "label": "Move project up",
      "mnemonic": -1,
      "accel": "Ctrl-Shift-Up"
     },
     {
      "type": "item",
      "id": "idMenuProjectDown",
      "label": "Move project down",
      "mnemonic": -1,
      "accel": "Ctrl-Shift-Down"
     },
     {
      "type": "sep"
     },
     {
      "type": "item",
      "id": "idMenuPriorProject",
      "label": "Activate prior project",
      "mnemonic": -1,
      "accel": "Alt-F5"
     },
     {
      "type": "item",
      "id": "idMenuNextProject",
      "label": "Activate next project",
      "mnemonic": -1,
      "accel": "Alt-F6"
     },
     {
      "type": "sep"
     },
     {
      "type": "item",
      "id": "idMenuViewCategorize",
      "label": "Categorize by file types",
      "mnemonic": -1,
      "checkable": true,
      "checked": true
     },
     {
      "type": "item",
      "id": "idMenuViewUseFolders",
      "label": "Display folders as on disk",
      "mnemonic": -1,
      "checkable": true,
      "checked": true
     },
     {
      "type": "item",
      "id": "idMenuViewHideFolderName",
      "label": "Hide folder name",
      "mnemonic": -1,
      "checkable": true
     },
     {
      "type": "item",
      "id": "idMenuViewSortAlphabetically",
      "label": "Sort projects alphabetically",
      "mnemonic": -1,
      "checkable": true
     }
    ]
   },
   {
    "type": "item",
    "id": "idMenuProjectBuildOptions",
    "label": "Build options...",
    "mnemonic": -1,
    "help": "Set the project's build options"
   },
   {
    "type": "item",
    "id": "idMenuExecParams",
    "label": "Set programs' arguments...",
    "mnemonic": 4,
    "help": "Set execution parameters for the targets of this project"
   },
   {
    "type": "item",
    "id": "idMenuProjectNotes",
    "label": "Notes...",
    "mnemonic": -1
   },
   {
    "type": "item",
    "id": "idMenuProjectProperties",
    "label": "Properties...",
    "mnemonic": -1
   }
  ]
 },
 {
  "id": "compiler_menu",
  "label": "Build",
  "mnemonic": 0,
  "items": [
   {
    "type": "item",
    "id": "idCompilerMenuCompile",
    "label": "Build",
    "mnemonic": 0,
    "accel": "Ctrl-F9",
    "help": "Build current project",
    "bitmap": "compiler/compile"
   },
   {
    "type": "item",
    "id": "idCompilerMenuCompileFile",
    "label": "Compile current file",
    "mnemonic": 16,
    "accel": "Ctrl-Shift-F9",
    "help": "Compile current file"
   },
   {
    "type": "item",
    "id": "idCompilerMenuRun",
    "label": "Run",
    "mnemonic": 0,
    "accel": "Ctrl-F10",
    "help": "Run current project",
    "bitmap": "compiler/run"
   },
   {
    "type": "item",
    "id": "idCompilerMenuCompileAndRun",
    "label": "Build and run",
    "mnemonic": 3,
    "accel": "F9",
    "help": "Build and run current project",
    "bitmap": "compiler/compile_run"
   },
   {
    "type": "item",
    "id": "idCompilerMenuRebuild",
    "label": "Rebuild",
    "mnemonic": 6,
    "accel": "Ctrl-F11",
    "help": "Rebuild current project",
    "bitmap": "compiler/rebuild"
   },
   {
    "type": "item",
    "id": "idCompilerMenuClean",
    "label": "Clean",
    "mnemonic": 0,
    "help": "Clean current project"
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idCompilerMenuBuildWorkspace",
    "label": "Build workspace",
    "mnemonic": 6,
    "help": "Build all projects in workspace"
   },
   {
    "type": "item",
    "id": "idCompilerMenuRebuildWorkspace",
    "label": "Rebuild workspace",
    "mnemonic": 3,
    "help": "Rebuild all projects in workspace"
   },
   {
    "type": "item",
    "id": "idCompilerMenuCleanWorkspace",
    "label": "Clean workspace",
    "mnemonic": -1,
    "help": "Clean current project (dependencies too)"
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idCompilerMenuKillProcess",
    "label": "Abort",
    "mnemonic": 0,
    "help": "Abort the running build process",
    "bitmap": "compiler/stop"
   },
   {
    "type": "sep"
   },
   {
    "type": "menu",
    "id": "idCompilerMenuErrors",
    "label": "Errors",
    "mnemonic": 0,
    "items": [
     {
      "type": "item",
      "id": "idCompilerMenuPreviousError",
      "label": "Previous error",
      "mnemonic": 0,
      "accel": "Alt-F1",
      "help": "Go to previous compilation error"
     },
     {
      "type": "item",
      "id": "idCompilerMenuNextError",
      "label": "Next error",
      "mnemonic": 0,
      "accel": "Alt-F2",
      "help": "Go to next compilation error"
     },
     {
      "type": "sep"
     },
     {
      "type": "item",
      "id": "idCompilerMenuClearErrors",
      "label": "Clear all errors",
      "mnemonic": 0,
      "help": "Clear all compilation errors"
     }
    ]
   },
   {
    "type": "menu",
    "id": "idCompilerMenuSelectTarget",
    "label": "Select target",
    "mnemonic": -1,
    "items": [
     {
      "type": "item",
      "id": "idMenuSelectTargetDialog",
      "label": "Select target",
      "mnemonic": -1,
      "help": "Shows a dialog with all targets",
      "bitmap": "sdk/select_target"
     },
     {
      "type": "sep"
     },
     {
      "type": "item",
      "id": "idCompilerTarget0",
      "label": "Debug",
      "mnemonic": -1,
      "radio": true,
      "checked": true
     },
     {
      "type": "item",
      "id": "idCompilerTarget1",
      "label": "Release",
      "mnemonic": -1,
      "radio": true
     }
    ]
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idCompilerMenuExportMakefile",
    "label": "Export Makefile",
    "mnemonic": 1,
    "help": "Export Makefile so that you can build the program from the command line",
    "enabled": false
   }
  ]
 },
 {
  "id": "debugger_menu",
  "label": "Debug",
  "mnemonic": 0,
  "items": [
   {
    "type": "menu",
    "id": "idDebuggerMenuActive",
    "label": "Active debuggers",
    "mnemonic": -1,
    "items": [
     {
      "type": "item",
      "id": "idDebuggerActiveGDB",
      "label": "GDB/CDB debugger : Default",
      "mnemonic": -1,
      "radio": true,
      "checked": true
     }
    ]
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idDebuggerMenuDebug",
    "label": "Start / Continue",
    "mnemonic": 0,
    "accel": "F8",
    "help": "Run current project in debugger",
    "bitmap": "core/dbg/run"
   },
   {
    "type": "item",
    "id": "idDebuggerMenuBreak",
    "label": "Break debugger",
    "mnemonic": -1,
    "help": "Break the debuggee in order to examine its state",
    "bitmap": "core/dbg/pause"
   },
   {
    "type": "item",
    "id": "idDebuggerMenuStop",
    "label": "Stop debugger",
    "mnemonic": -1,
    "accel": "Shift-F8",
    "help": "Stop current debugging session",
    "bitmap": "core/dbg/stop"
   },
   {
    "type": "item",
    "id": "idDebuggerMenuRunToCursor",
    "label": "Run to cursor",
    "mnemonic": -1,
    "accel": "F4",
    "help": "Run program until it reaches the current line",
    "bitmap": "core/dbg/run_to"
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idDebuggerMenuNext",
    "label": "Next line",
    "mnemonic": -1,
    "accel": "F7",
    "help": "Execute the next line of code",
    "bitmap": "core/dbg/next"
   },
   {
    "type": "item",
    "id": "idDebuggerMenuStep",
    "label": "Step into",
    "mnemonic": -1,
    "accel": "Shift-F7",
    "help": "Execute the next line of code, but step inside functions",
    "bitmap": "core/dbg/step"
   },
   {
    "type": "item",
    "id": "idDebuggerMenuStepOut",
    "label": "Step out",
    "mnemonic": -1,
    "accel": "Ctrl-F7",
    "help": "Continue execution until the current frame exits",
    "bitmap": "core/dbg/step_out"
   },
   {
    "type": "item",
    "id": "idDebuggerMenuNextInstr",
    "label": "Next instruction",
    "mnemonic": -1,
    "accel": "Alt-F7",
    "help": "Execute the next assembly instruction",
    "bitmap": "core/dbg/next_inst"
   },
   {
    "type": "item",
    "id": "idDebuggerMenuStepIntoInstr",
    "label": "Step into instruction",
    "mnemonic": -1,
    "accel": "Shift-Alt-F7",
    "help": "Execute the next assembly instruction, if it is a function call step into it",
    "bitmap": "core/dbg/step_inst"
   },
   {
    "type": "item",
    "id": "idDebuggerMenuSetNextStatement",
    "label": "Set next statement",
    "mnemonic": -1,
    "help": "Move the Program counter to the selected/current line"
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idDebuggerMenuToggleBreakpoint",
    "label": "Toggle breakpoint",
    "mnemonic": -1,
    "accel": "F5",
    "help": "Toggle breakpoint in current line"
   },
   {
    "type": "item",
    "id": "idDebuggerMenuRemoveAllBreakpoints",
    "label": "Remove all breakpoints",
    "mnemonic": -1,
    "help": "Remove all breakpoints"
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idDebuggerMenuAddSymbolFile",
    "label": "Add symbol file",
    "mnemonic": -1,
    "help": "Adds symbols from another file"
   },
   {
    "type": "menu",
    "id": "idDebuggingWindows",
    "label": "Debugging windows",
    "mnemonic": -1,
    "items": [
     {
      "type": "item",
      "id": "idDebuggerWinBreakpoints",
      "label": "Breakpoints",
      "mnemonic": -1,
      "checkable": true
     },
     {
      "type": "item",
      "id": "idDebuggerWinCPURegisters",
      "label": "CPU Registers",
      "mnemonic": -1,
      "checkable": true
     },
     {
      "type": "item",
      "id": "idDebuggerWinCallStack",
      "label": "Call stack",
      "mnemonic": -1,
      "checkable": true
     },
     {
      "type": "item",
      "id": "idDebuggerWinDisassembly",
      "label": "Disassembly",
      "mnemonic": -1,
      "checkable": true
     },
     {
      "type": "item",
      "id": "idDebuggerWinMemory",
      "label": "Memory dump",
      "mnemonic": -1,
      "checkable": true
     },
     {
      "type": "item",
      "id": "idDebuggerWinThreads",
      "label": "Running threads",
      "mnemonic": -1,
      "checkable": true
     },
     {
      "type": "item",
      "id": "idDebuggerWinWatches",
      "label": "Watches",
      "mnemonic": -1,
      "checkable": true
     }
    ]
   },
   {
    "type": "menu",
    "id": "idDebuggerInfo",
    "label": "Information",
    "mnemonic": -1,
    "items": [
     {
      "type": "item",
      "id": "idDebuggerInfoFrame",
      "label": "Current stack frame",
      "mnemonic": -1
     },
     {
      "type": "item",
      "id": "idDebuggerInfoDLL",
      "label": "Loaded libraries",
      "mnemonic": -1
     },
     {
      "type": "item",
      "id": "idDebuggerInfoFiles",
      "label": "Targets and files",
      "mnemonic": -1
     },
     {
      "type": "item",
      "id": "idDebuggerInfoFPU",
      "label": "FPU status",
      "mnemonic": -1
     },
     {
      "type": "item",
      "id": "idDebuggerInfoSignals",
      "label": "Signal handling",
      "mnemonic": -1
     }
    ]
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idDebuggerMenuAttachToProcess",
    "label": "Attach to process...",
    "mnemonic": -1,
    "help": "Attach to an external running process"
   },
   {
    "type": "item",
    "id": "idDebuggerMenuDetach",
    "label": "Detach",
    "mnemonic": -1,
    "help": "Detach from running process"
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idDebuggerMenuSendCommand",
    "label": "Send user command to debugger",
    "mnemonic": -1,
    "help": "Sends a user-defined command to the debugger"
   }
  ]
 },
 {
  "id": "menu_fortran",
  "label": "Fortran",
  "mnemonic": -1,
  "items": [
   {
    "type": "item",
    "id": "idFortranGotoDeclaration",
    "label": "Jump to declaration",
    "mnemonic": -1,
    "accel": "Ctrl-Shift-D"
   },
   {
    "type": "item",
    "id": "idFortranGotoSubmodule",
    "label": "Jump to submodule procedure",
    "mnemonic": -1
   },
   {
    "type": "item",
    "id": "idFortranJumpBack",
    "label": "Jump back",
    "mnemonic": -1,
    "accel": "Ctrl-Alt-Left"
   },
   {
    "type": "item",
    "id": "idFortranJumpForward",
    "label": "Jump forward",
    "mnemonic": -1,
    "accel": "Ctrl-Alt-Right"
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idFortranGenerateMakefile",
    "label": "Generate Makefile",
    "mnemonic": -1
   },
   {
    "type": "item",
    "id": "idFortranChangeCase",
    "label": "Change case...",
    "mnemonic": -1
   },
   {
    "type": "item",
    "id": "idFortranTab2Space",
    "label": "Tab2Space",
    "mnemonic": -1
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idFortranBindTo",
    "label": "Bind to...",
    "mnemonic": -1
   },
   {
    "type": "item",
    "id": "idFortranFormatIndent",
    "label": "Format indent",
    "mnemonic": -1
   }
  ]
 },
 {
  "id": "menu_wxsmith",
  "label": "wxSmith",
  "mnemonic": -1,
  "items": [
   {
    "type": "item",
    "id": "idWxsAddWxFrame",
    "label": "Add wxFrame",
    "mnemonic": -1
   },
   {
    "type": "item",
    "id": "idWxsAddWxDialog",
    "label": "Add wxDialog",
    "mnemonic": -1
   },
   {
    "type": "item",
    "id": "idWxsAddWxPanel",
    "label": "Add wxPanel",
    "mnemonic": -1
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idWxsImportXrc",
    "label": "Import XRC file",
    "mnemonic": -1
   },
   {
    "type": "item",
    "id": "idWxsAddResource",
    "label": "Add resource...",
    "mnemonic": -1
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idWxsConfigure",
    "label": "Configure...",
    "mnemonic": -1
   }
  ]
 },
 {
  "id": "menu_tools",
  "label": "Tools",
  "mnemonic": 0,
  "items": [
   {
    "type": "item",
    "id": "idPluginsCodeStats",
    "label": "Code statistics",
    "mnemonic": -1,
    "help": "Count code, comment and empty lines"
   },
   {
    "type": "item",
    "id": "idPluginsTodo",
    "label": "To-Do list",
    "mnemonic": -1,
    "help": "List the TODO/FIXME/NOTE items in the open files"
   },
   {
    "type": "item",
    "id": "idPluginsThreadSearch",
    "label": "Thread search",
    "mnemonic": -1
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idToolsConfigure",
    "label": "Configure tools...",
    "mnemonic": -1
   }
  ]
 },
 {
  "id": "menu_toolsplus",
  "label": "Tools+",
  "mnemonic": -1,
  "items": [
   {
    "type": "item",
    "id": "idToolsPlusConfigure",
    "label": "Configure...",
    "mnemonic": -1
   }
  ]
 },
 {
  "id": "menu_plugins",
  "label": "Plugins",
  "mnemonic": 1,
  "items": [
   {
    "type": "item",
    "id": "idPluginsAStyle",
    "label": "Source code formatter (AStyle)",
    "mnemonic": -1,
    "accel": "Ctrl-Shift-U",
    "help": "Format the current source file"
   },
   {
    "type": "item",
    "id": "idPluginsAbbreviations",
    "label": "Expand abbreviation",
    "mnemonic": -1,
    "accel": "Ctrl-J",
    "help": "Expand the keyword before the caret"
   },
   {
    "type": "item",
    "id": "idPluginsCodeComplete",
    "label": "Code completion",
    "mnemonic": -1,
    "accel": "Ctrl-Space"
   },
   {
    "type": "item",
    "id": "idPluginsOccurrences",
    "label": "Occurrences highlighting",
    "mnemonic": -1,
    "checkable": true,
    "checked": true
   },
   {
    "type": "item",
    "id": "idPluginsGames",
    "label": "C::B games",
    "mnemonic": -1,
    "help": "Play cbTris or Snake"
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idPluginsManagePlugins",
    "label": "Manage plugins...",
    "mnemonic": 7,
    "help": "Enable or disable plugins for the next session",
    "bitmap": "core/manage_plugins"
   }
  ]
 },
 {
  "id": "menu_doxyblocks",
  "label": "DoxyBlocks",
  "mnemonic": -1,
  "items": [
   {
    "type": "item",
    "id": "idDoxyBlockComment",
    "label": "Block comment",
    "mnemonic": -1,
    "accel": "Ctrl-Alt-B"
   },
   {
    "type": "item",
    "id": "idDoxyLineComment",
    "label": "Line comment",
    "mnemonic": -1,
    "accel": "Ctrl-Alt-L"
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idDoxyExtract",
    "label": "Extract documentation",
    "mnemonic": -1,
    "accel": "Ctrl-Alt-E"
   },
   {
    "type": "item",
    "id": "idDoxyRunHTML",
    "label": "Run HTML",
    "mnemonic": -1,
    "accel": "Ctrl-Alt-H"
   },
   {
    "type": "item",
    "id": "idDoxyRunCHM",
    "label": "Run CHM",
    "mnemonic": -1
   },
   {
    "type": "sep"
   },
   {
    "type": "item",
    "id": "idDoxyWizard",
    "label": "Run doxywizard",
    "mnemonic": -1
   },
   {
    "type": "item",
    "id": "idDoxyConfig",
    "label": "Open preferences...",
    "mnemonic": -1
   }
  ]
 },
 {
  "id": "menu_settings",
  "label": "Settings",
  "mnemonic": 0,
  "items": [
   {
    "type": "item",
    "id": "idSettingsEnvironment",
    "label": "Environment...",
    "mnemonic": 0,
    "help": "Change environment settings"
   },
   {
    "type": "item",
    "id": "idSettingsEditor",
    "label": "Editor...",
    "mnemonic": 1,
    "help": "Change editor's settings"
   },
   {
    "type": "item",
    "id": "idSettingsCompiler",
    "label": "Compiler...",
    "mnemonic": 0,
    "help": "Change compiler settings"
   },
   {
    "type": "item",
    "id": "idSettingsDebugger",
    "label": "Debugger...",
    "mnemonic": 0,
    "help": "Change debugger settings"
   },
   {
    "type": "item",
    "id": "idSettingsGlobalUserVars",
    "label": "Global variables...",
    "mnemonic": 0,
    "help": "Change global compiler variables"
   },
   {
    "type": "item",
    "id": "idSettingsBackticks",
    "label": "Backtick Cache...",
    "mnemonic": 0,
    "help": "Show the list of all backtick expressions present in the cache"
   },
   {
    "type": "item",
    "id": "idSettingsScripting",
    "label": "Scripting...",
    "mnemonic": 0,
    "help": "Change scripting settings"
   }
  ]
 },
 {
  "id": "menu_help",
  "label": "Help",
  "mnemonic": 0,
  "items": [
   {
    "type": "item",
    "id": "wxID_ABOUT",
    "label": "About...",
    "mnemonic": 0,
    "help": "About Code::Blocks",
    "bitmap": "core/help_info"
   },
   {
    "type": "item",
    "id": "idHelpTips",
    "label": "Tips",
    "mnemonic": 0,
    "help": "Tips on using Code::Blocks",
    "bitmap": "core/help_idea"
   },
   {
    "type": "menu",
    "id": "idHelpPlugins",
    "label": "Plugins",
    "mnemonic": 0,
    "items": []
   }
  ]
 }
];
